class darkTheme:
    font_main           = "Segoe UI Light"
    bg                  = "#2d2d30"
    fg                  = "white"
    fg_footer           = "white"
    button_fg           = "#787878"
    button_bg           = "#282828"
    button_bg_active    = "#1E1E1E"
    footer_bg           = "#730064"
    relief              = "flat"
    border_width        = "0"
    height              = "2"

class lightTheme:
    font_main           = "Segoe UI Light"
    bg                  = "white"
    fg                  = "black"
    fg_footer           = "black"
    button_fg           = "#787878"
    button_bg           = "#F0F0F0"
    button_bg_active    = "#DCDCDC"
    footer_bg           = "#FF8AFF"
    relief              = "flat"
    border_width        = "0"
    height              = "2"

class retroTheme:
    font_main           = "MS Sans Serif"
    bg                  = "#C3C3C3"
    fg                  = "black"
    fg_footer           = "white"
    button_fg           = "black"
    button_bg           = "#B4B4B4"
    button_bg_active    = "#A0A0A0"
    footer_bg           = "#000080"
    relief              = "raised"
    border_width        = "1"
    height              = "2"

class simsTheme:
    font_main           = "Comic Sans MS"
    bg                  = "#01126C"
    fg                  = "white"
    fg_footer           = "white"
    button_fg           = "white"
    button_bg           = "#0061A5"
    button_bg_active    = "#07286A"
    footer_bg           = "#000138"
    relief              = "raised"
    border_width        = "1"
    height              = "1"

class pipTheme:
    font_main           = "Fixedsys"
    bg                  = "black"
    fg                  = "#5DBE4E"
    fg_footer           = "#827541"
    button_fg           = "black"
    button_bg           = "#5DBE4E"
    button_bg_active    = "#5DBE4E"
    footer_bg           = "#3E3726"
    relief              = "flat"
    border_width        = "0"
    height              = "3"

class nokiaTheme:
    font_main           = "Fixedsys"
    bg                  = "#97BB73"
    fg                  = "black"
    fg_footer           = "black"
    button_fg           = "#97BB73"
    button_bg           = "black"
    button_bg_active    = "black"
    footer_bg           = "#97BB73"
    relief              = "flat"
    border_width        = "0"
    height              = "3"

class starui:
    # Placeholder Values
    font_main           = "Segoe UI Light"
    bg                  = "#2d2d30"
    fg                  = "white"
    fg_footer           = "white"
    button_fg           = "#787878"
    button_bg           = "#282828"
    button_bg_active    = "#1E1E1E"
    footer_bg           = "#730064"
    relief              = "flat"
    border_width        = "0"
    height              = "2"